<?php /** @var $block \HayesMarketing\Gallery\Block\Photoset */ ?>
<div class="row">
    <ul class="polaroids large-4 small-2">
        <?php foreach ($block->getPhotosets() as $photoset): ?>
            <li>
                <?php /** @var $photoset \HayesMarketing\Gallery\Model\Photoset */ ?>
                <a href="<?php echo "gallery/" . $photoset->getUrlKey() ?>" title="<?php echo $photoset->getTitle(); ?>">
                    <img src="<?php echo $photoset->getPhotoUrl() ?>">
                </a>
            </li>
        <?php endforeach; ?>
    </ul>
</div>



