<?php
/** @var $block \HayesMarketing\Gallery\Block\View */
/** @var $photo \HayesMarketing\Gallery\Model\Photo */
?>

<div id="slider" class="flexslider">
    <ul class="slides">
        <?php foreach ($block->getPhotos() as $photo): ?>
            <li>
                <h2 class="photo-title"> <?php echo $photo->getTitle() ?> </h2>
                <div class="photo-tags">
                    <ul>
                        <?php $tags = explode(',', $photo->getTags()); ?>
                        <?php foreach ($tags as $tag): ?>
                            <li><a href=""> <?php echo $tag; ?></a></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <img src='<?php echo $photo->getPhotoUrl() ?>' alt="Demo">
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<div id="carousel" class="flexslider">
    <ul class="slides">
        <?php foreach ($block->getPhotos() as $photo): ?>
            <li>
                <img src='<?php echo $photo->getPhotoUrl(); ?>' alt="Demo">
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    require(['jquery','flexslider'],function($){
        $(window).ready(function() {
            // The slider being synced must be initialized first
            $('#carousel').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: true,
                slideshow: false,
                itemWidth: 210,
                itemMargin: 5,
                asNavFor: '#slider'
            });

            $('#slider').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: true,
                slideshow: false,
                sync: "#carousel"
            });
        });
    });
</script>