<?php /** @var $block \HayesMarketing\Gallery\Block\View */ ?>

<div id="slider" class="flexslider">
    <ul class="slides">
        <?php foreach ($block->getPhotos() as $photo): ?>
            <?php /** @var $photo \HayesMarketing\Gallery\Model\Photo */ ?>
            <li>
                <div class="main-photo">
                    <p class="photo-title"> <?php echo $photo->getTitle() ?> </p>
                    <p>Tag One</p>
                </div>
                <img src='<?php echo $photo->getPhotoUrl() ?>' alt="Demo">
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<div id="carousel" class="flexslider">
    <ul class="slides">
        <?php foreach ($block->getPhotos() as $photo): ?>
            <li>
                <img src='<?php echo $photo->getPhotoUrl(); ?>' alt="Demo">
            </li>
        <?php endforeach; ?>
    </ul>
</div>

<script type="text/javascript">
    require(['jquery','flexslider'],function($){
        $(window).ready(function() {
            // The slider being synced must be initialized first
            $('#carousel').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: true,
                slideshow: false,
                itemWidth: 210,
                itemMargin: 5,
                asNavFor: '#slider'
            });

            $('#slider').flexslider({
                animation: "slide",
                controlNav: false,
                animationLoop: true,
                slideshow: false,
                sync: "#carousel"
            });
        });
    });
</script>